import React from 'react';
import { TOOL_KEYWORDS } from '../data/seoKeywords';
import { ToolDefinition } from '../types';

const paragraph = (parts: string[]) => parts.join(' ');

export const ToolSeoContent: React.FC<{ tool: ToolDefinition }> = ({ tool }) => {
  const kw = TOOL_KEYWORDS[tool.slug];
  const relatedNames = tool.relatedToolSlugs.map((slug) => slug.replace(/-/g, ' ')).join(', ');
  const content = [
    paragraph([`Looking for a ${kw?.primary || tool.title.toLowerCase()} that works without a complicated signup? FreeToolBox provides ${tool.title.toLowerCase()} directly in a modern web browser.`, tool.shortIntro, `The workflow is designed around a simple goal: ${kw?.intent || tool.description}`]),
    paragraph([`What makes this ${tool.title.toLowerCase()} useful is the combination of a focused interface and local browser processing.`, tool.description, `For everyday tasks, this means you can choose a file or enter data, apply the available settings, preview the result when supported, and download the output without sending the working file to a remote conversion queue.`]),
    paragraph([`Common reasons to use a ${kw?.primary || tool.title.toLowerCase()} include speed, convenience and privacy.`, `It is useful when you need a quick result on a laptop, desktop or modern mobile browser and do not want to install a separate utility.`, `Because the page explains supported formats and settings before processing, you can make a more informed choice about the output you need.`]),
    paragraph([`For the best result, start with the original file or cleanest source available.`, `Then follow the ${tool.howToSteps.length}-step workflow shown above and use the settings that match your intended output.`, tool.howToSteps.map((s) => `${s.step}) ${s.title}: ${s.description}`).join(' ')]),
    paragraph([`Supported formats and specifications matter when converting or optimizing digital files.`, `This tool accepts ${tool.supportedFormats.input.join(', ')} and can produce ${tool.supportedFormats.output.join(', ')}.`, `If your target application has a specific format requirement, choose the matching output before downloading and keep the original source file until you have confirmed the result.`]),
    paragraph([`Privacy is also part of the FreeToolBox workflow.`, `The tool is designed for client-side processing where practical, so the working data stays in the browser during normal use.`, `You should still use a current browser and avoid sharing sensitive information with any online service unless you understand its data handling.`, `For site-wide privacy details, review the Privacy Policy linked from this page.`]),
    paragraph([`The practical uses of ${tool.title.toLowerCase()} vary by workflow.`, ...tool.educationalContent.useCases, `These examples illustrate why a focused utility can be useful for students, creators, office workers, developers and small businesses that need an occasional conversion or formatting task.`]),
    paragraph([`Under the hood, ${tool.educationalContent.technicalDetails}`, `Understanding the underlying file format or processing method can help you choose sensible settings and avoid unnecessary quality loss.`, `When quality, compatibility or file size matters, compare the output with the source before publishing or sending it to another person.`]),
    paragraph([`After completing this task, you may also need ${relatedNames || 'another FreeToolBox utility'}.`, `The related tools section below creates a direct path to complementary tasks, while the category page groups similar utilities together.`, `This structure is intended to make it easier to move from one job to the next without repeatedly searching for another utility.`]),
    paragraph([`Frequently asked questions below address common setup and usage questions for ${tool.title.toLowerCase()}.`, `Read them if you are unsure about formats, privacy, output quality or recommended settings.`, `If the tool does not support your exact requirement, return to the category directory and choose a utility with the appropriate input and output formats.`]),
    paragraph([`A few simple quality checks can prevent avoidable problems.`, `Confirm the input extension before starting, keep an untouched copy of important source files, and inspect the downloaded result before publishing it.`, `For image workflows, compare dimensions and visual quality. For PDF workflows, open the resulting document and check page order. For text and developer utilities, validate the final content in the application where it will be used.`, `These small checks are especially useful when a file will be sent to a client, uploaded to a website or used as part of a larger production workflow.`]),
    paragraph([`If a result does not look right, try the simplest troubleshooting sequence first.`, `Reload the page with a current browser, use a smaller test file, confirm the input format, and repeat the operation with default settings before changing advanced options.`, `Browser memory can become a limiting factor when very large images or many PDF pages are processed at once, so splitting a large job into smaller batches can help.`, `If the browser blocks a download or clipboard action, allow the relevant permission and retry the action directly from the tool interface.`]),
  ];
  return <section className="mb-14" aria-labelledby="seo-guide"><div className="max-w-4xl mx-auto"><h2 id="seo-guide" className="text-2xl sm:text-3xl font-bold text-slate-900 dark:text-white mb-5">Complete Guide to {tool.title}</h2><div className="space-y-5 text-sm sm:text-base leading-7 text-slate-600 dark:text-slate-400">{content.map((p, i) => <p key={i}>{p}</p>)}</div></div></section>;
};
